# -*- coding: utf-8 -*-
"""osf_preprints_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZIDxupZtJ4Rwq5xmdE48Fff5bgIXyNSV
"""

import requests
import json
import time

ti = time.time()

preprintsApiUrl = "https://api.osf.io/v2/providers/preprints/africarxiv/preprints/?page[size]=57"
preprintsRequest = requests.get( url = preprintsApiUrl )
preprintsRequestContent = json.loads( preprintsRequest.content )

for preprint in preprintsRequestContent['data']:
  print( preprint['attributes']['date_published'] )
  print( preprint['attributes']['title'] )
  #print( preprint['attributes']['description'] )
  print( preprint['links']['html'] )
  print( preprint['links']['preprint_doi'] )
  
  for subject in preprint['attributes']['subjects']:
    for subj in subject:
      print( subj['text'] )
    print( '\n' )
    
  authorApiUrl = preprint['relationships']['contributors']['links']['related']['href']
  authorRequest = requests.get( url = authorApiUrl )
  authorRequestContent = json.loads( authorRequest.content )
  
  for preprintAuthor in authorRequestContent['data']:
    print( preprintAuthor['embeds']['users']['data']['links']['html'] )
    print( preprintAuthor['embeds']['users']['data']['attributes']['full_name'] )
    
  print( '\n' )
    
print( time.time - ti )